version: "3.3"
services:

  dyn-form-be:
    build:
      context: .

    container_name: dyn-form-be
    volumes:
      - m2:/root/.m2
    expose:
      - "8080"
    ports:
      - "8096:8080"
      
volumes:
  m2:
