version: "3.3"
services:
  dyn-form-demo-postgres:
    image: 'postgres:13.1-alpine'
    container_name: dyn-form-postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=testdb
    restart: unless-stopped

  dyn-form-demo:
    build:
      context: ../..

    container_name: dyn-form-demo
    expose:
      - "8080"
    ports:
      - "8096:8080"
    depends_on:
      - dyn-form-demo-postgres

  dyn-form-fe:
    image: fabiobiffoli/dyn-form-fe
    container_name: dyn-form-fe
    expose:
      - "80"
    ports:
      - "3000:80"
    depends_on:
      - dyn-form-demo
      
volumes:
  postgres-data:
